/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject1;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Zero
 */
public class EmployeeList extends javax.swing.JFrame {
    StoreManage manage = new StoreManage();
    List<Employee> listEmployee = manage.readEmployeeFromFile();
    /**
     * Creates new form EmployeeList
     */
    public EmployeeList() {
        initComponents();
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);    
        Vector data = null;
        for(Employee emp:listEmployee)
        {
            data = new Vector();
            data.add(emp.getEmpID());
            data.add(emp.getEmpName());
            data.add(emp.getEmpPhone());
            data.add(emp.getPosition());

            tblModel.addRow(data);
        }
        this.Employee_tb.setModel(tblModel);
    }
    
    private String header[] = {"ID","Name","Phone","Position"};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_Search = new javax.swing.JTextField();
        Search_bt = new javax.swing.JButton();
        tf_empID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_empPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_Position = new javax.swing.JTextField();
        tf_empName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Delete_bt = new javax.swing.JButton();
        Edit_bt = new javax.swing.JButton();
        Add_bt = new javax.swing.JButton();
        Clear_bt = new javax.swing.JButton();
        Return_bt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Employee_tb = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Employee list");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 14, 340, 84));

        tf_Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_Search.setToolTipText("");
        jPanel1.add(tf_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 116, 584, 43));

        Search_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search_bt.setForeground(new java.awt.Color(0, 0, 204));
        Search_bt.setText("SEARCH");
        Search_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btActionPerformed(evt);
            }
        });
        jPanel1.add(Search_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 113, 103, 50));
        jPanel1.add(tf_empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 200, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 199, -1, -1));
        jPanel1.add(tf_empPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 190, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Phone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Position");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));
        jPanel1.add(tf_Position, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 190, -1));
        jPanel1.add(tf_empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 250, 190, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 256, -1, 25));

        Delete_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete_bt.setForeground(new java.awt.Color(0, 0, 204));
        Delete_bt.setText("DELETE");
        Delete_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btActionPerformed(evt);
            }
        });
        jPanel1.add(Delete_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 103, 43));

        Edit_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Edit_bt.setForeground(new java.awt.Color(0, 0, 204));
        Edit_bt.setText("EDIT");
        Edit_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_btActionPerformed(evt);
            }
        });
        jPanel1.add(Edit_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 103, 43));

        Add_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add_bt.setForeground(new java.awt.Color(0, 0, 204));
        Add_bt.setText("ADD");
        Add_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btActionPerformed(evt);
            }
        });
        jPanel1.add(Add_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 103, 43));

        Clear_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear_bt.setForeground(new java.awt.Color(0, 0, 204));
        Clear_bt.setText("CLEAR");
        Clear_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btActionPerformed(evt);
            }
        });
        jPanel1.add(Clear_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 103, 43));

        Return_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Return_bt.setForeground(new java.awt.Color(0, 51, 204));
        Return_bt.setText("RETURN");
        Return_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_btActionPerformed(evt);
            }
        });
        jPanel1.add(Return_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 103, 43));

        Employee_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone", "Position"
            }
        ));
        Employee_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Employee_tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Employee_tb);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 930, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject1/emp.jpg"))); // NOI18N
        jLabel4.setFocusable(false);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -80, 1090, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btActionPerformed
        if(tf_empPhone.getText().equals("")||tf_empID.getText().equals("")||tf_empName.getText().equals("")||tf_Position.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Not enough information.");
        }
        else
        {
            if(manage.EmployeeIDValid(this.tf_empID.getText(), listEmployee)==false){
                JOptionPane.showMessageDialog(this,"Employee Already Exist.");
            }else{
                Employee employee = new Employee();
                employee.setEmpID(this.tf_empID.getText());
                employee.setEmpName(this.tf_empName.getText());
                employee.setEmpPhone(this.tf_empPhone.getText());   
                employee.setPosition(this.tf_Position.getText());     
                listEmployee.add(employee);
    
                manage.writeEmployeeToFile(listEmployee);       
            
                DefaultTableModel tblModel = new DefaultTableModel(header, 0);    
                Vector data = null;
                for(Employee emp:listEmployee)
                {
                    data = new Vector();
                    data.add(emp.getEmpID());
                    data.add(emp.getEmpName());
                    data.add(emp.getEmpPhone());
                    data.add(emp.getPosition());
                
                    tblModel.addRow(data);
                }
                this.Employee_tb.setModel(tblModel);
                JOptionPane.showMessageDialog(this,"Adding successful.");
            }
            
        }
    }//GEN-LAST:event_Add_btActionPerformed

    private void Employee_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee_tbMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel tbt = (DefaultTableModel) Employee_tb.getModel();
        int index = Employee_tb.getSelectedRow();
        String tbtEmpID = tbt.getValueAt(Employee_tb.getSelectedRow(), 0).toString();
        String tbtEmpName = tbt.getValueAt(Employee_tb.getSelectedRow(), 1).toString();
        String tbtPhone = tbt.getValueAt(Employee_tb.getSelectedRow(),2).toString();
        String tbtPosition = tbt.getValueAt(Employee_tb.getSelectedRow(), 3).toString();
        
        tf_empID.setText(tbtEmpID);
        tf_empName.setText(tbtEmpName);
        tf_empPhone.setText(tbtPhone);
        tf_Position.setText(tbtPosition);
    }//GEN-LAST:event_Employee_tbMouseClicked

    private void Delete_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btActionPerformed
        DefaultTableModel tbtModel = (DefaultTableModel) Employee_tb.getModel();
        
        if(Employee_tb.getSelectedRowCount()==1)
        {
            int i=Employee_tb.getSelectedRow();
            tbtModel.removeRow(Employee_tb.getSelectedRow());
            listEmployee.remove(i); 
            manage.writeEmployeeToFile(listEmployee);
        }
        else {
            if(Employee_tb.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"No Data.");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Chose A Row To Delete.");
            }
        }
    }//GEN-LAST:event_Delete_btActionPerformed

    private void Edit_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_btActionPerformed
        DefaultTableModel tbt = (DefaultTableModel) Employee_tb.getModel();
        if(Employee_tb.getSelectedRowCount()==1)
        {
            String empID = tf_empID.getText();
            String empName = tf_empName.getText();
            String empPhone = tf_empPhone.getText();
            String position = tf_Position.getText();
            listEmployee.set(Employee_tb.getSelectedRow(), new Employee(empID,empName,empPhone,position));
            manage.writeEmployeeToFile(listEmployee);
            
            tbt.setValueAt(empID, Employee_tb.getSelectedRow(), 0);
            tbt.setValueAt(empName, Employee_tb.getSelectedRow(), 1);        
            tbt.setValueAt(empPhone, Employee_tb.getSelectedRow(), 2);
            tbt.setValueAt(position, Employee_tb.getSelectedRow(), 3);
        }
        else{
            JOptionPane.showMessageDialog(this,"Chose A Row To Edit.");
        }
    }//GEN-LAST:event_Edit_btActionPerformed

    private void Clear_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btActionPerformed
        tf_empID.setText("");
        tf_empName.setText("");
        tf_empPhone.setText("");
        tf_Position.setText("");
    }//GEN-LAST:event_Clear_btActionPerformed

    private void Return_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_btActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_Return_btActionPerformed

    private void Search_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btActionPerformed
        String srch = tf_Search.getText();
    
        if (srch != null) {
            filter(srch);
        } else {
            JOptionPane.showMessageDialog(this,"Employee is not exist.");
        }
    }//GEN-LAST:event_Search_btActionPerformed
    
    private void filter(String query){
    DefaultTableModel tbtModel = (DefaultTableModel) Employee_tb.getModel();
    TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(tbtModel);
    Employee_tb.setRowSorter(tr);

    tr.setRowFilter(RowFilter.regexFilter(query));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_bt;
    private javax.swing.JButton Clear_bt;
    private javax.swing.JButton Delete_bt;
    private javax.swing.JButton Edit_bt;
    private javax.swing.JTable Employee_tb;
    private javax.swing.JButton Return_bt;
    private javax.swing.JButton Search_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tf_Position;
    private javax.swing.JTextField tf_Search;
    private javax.swing.JTextField tf_empID;
    private javax.swing.JTextField tf_empName;
    private javax.swing.JTextField tf_empPhone;
    // End of variables declaration//GEN-END:variables
}
