/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject1;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Zero
 */
public class ImportList extends javax.swing.JFrame {
    StoreManage manage = new StoreManage();
    List<Import> listimport = manage.readImportFromFile();
    /**
     * Creates new form Import
     */
    public ImportList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Search_bt = new javax.swing.JButton();
        tf_Search = new javax.swing.JTextField();
        tf_Cate = new javax.swing.JTextField();
        tf_spName = new javax.swing.JTextField();
        tf_Price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        tf_ImID = new javax.swing.JTextField();
        tf_PdName = new javax.swing.JTextField();
        tf_Unit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        Return_bt = new javax.swing.JButton();
        Clear_bt = new javax.swing.JButton();
        Delete_bt = new javax.swing.JButton();
        Edit_bt = new javax.swing.JButton();
        Add_bt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        import_tb = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Import");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, -1, -1));

        Search_bt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Search_bt.setText("SEARCH");
        Search_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btActionPerformed(evt);
            }
        });
        jPanel1.add(Search_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 66, 97, 34));
        jPanel1.add(tf_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 66, 436, 34));
        jPanel1.add(tf_Cate, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 141, 169, -1));
        jPanel1.add(tf_spName, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 190, 169, -1));
        jPanel1.add(tf_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 247, 169, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Category");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 139, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Supplier Name");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 188, -1, -1));

        label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label1.setText("Price");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 245, -1, -1));
        jPanel1.add(tf_ImID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 141, 169, -1));
        jPanel1.add(tf_PdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 169, -1));

        tf_Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_UnitActionPerformed(evt);
            }
        });
        jPanel1.add(tf_Unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 247, 169, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 139, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Toy Name");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 189, -1, 20));

        l.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l.setText("Unit");
        jPanel1.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 246, -1, 20));

        Return_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Return_bt.setText("RETURN");
        Return_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_btActionPerformed(evt);
            }
        });
        jPanel1.add(Return_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 314, 110, 45));

        Clear_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear_bt.setText("CLEAR");
        Clear_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btActionPerformed(evt);
            }
        });
        jPanel1.add(Clear_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 314, -1, 45));

        Delete_bt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Delete_bt.setText("DELETE");
        Delete_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btActionPerformed(evt);
            }
        });
        jPanel1.add(Delete_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 315, 80, 44));

        Edit_bt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Edit_bt.setText("EDIT");
        Edit_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_btActionPerformed(evt);
            }
        });
        jPanel1.add(Edit_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 315, 80, 44));

        Add_bt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Add_bt.setText("ADD");
        Add_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btActionPerformed(evt);
            }
        });
        jPanel1.add(Add_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 315, 90, 44));

        import_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Category", "Supplier", "Unit", "Price"
            }
        ));
        import_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                import_tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(import_tb);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 620, 187));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject1/import.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -200, 1060, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Return_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_btActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_Return_btActionPerformed

    private void Clear_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btActionPerformed
        // TODO add your handling code here:
        tf_ImID.setText("");
        tf_PdName.setText("");
        tf_Cate.setText("");
        tf_spName.setText("");
        tf_Unit.setText("");
        tf_Price.setText("");
    }//GEN-LAST:event_Clear_btActionPerformed

    private void Delete_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbtModel = (DefaultTableModel) import_tb.getModel();

        if(import_tb.getSelectedRowCount()==1)
        {
            int i=import_tb.getSelectedRow();
            tbtModel.removeRow(import_tb.getSelectedRow());
            listimport.remove(i);
            manage.writeImportToFile(listimport);
        }
        else {
            if(import_tb.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"No Data.");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Chose A Row To Delete.");
            }
        }
    }//GEN-LAST:event_Delete_btActionPerformed

    private void Edit_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_btActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbt = (DefaultTableModel) import_tb.getModel();
        if(import_tb.getSelectedRowCount()==1)
        {
            String imID = tf_ImID.getText();
            String pdName = tf_PdName.getText();
            String pdCate = tf_Cate.getText();
            String spName = tf_spName.getText();
            int pdUnit = Integer.parseInt(tf_Unit.getText());
            double pdPrice = Double.parseDouble(tf_Price.getText());

            listimport.set(import_tb.getSelectedRow(), new Import(imID,pdName,pdCate,spName,pdUnit,pdPrice));
            manage.writeImportToFile(listimport);

            tbt.setValueAt(imID, import_tb.getSelectedRow(), 0);
            tbt.setValueAt(pdName, import_tb.getSelectedRow(), 1);
            tbt.setValueAt(pdCate, import_tb.getSelectedRow(), 2);
            tbt.setValueAt(spName, import_tb.getSelectedRow(), 3);
            tbt.setValueAt(pdUnit, import_tb.getSelectedRow(), 4);
            tbt.setValueAt(pdPrice, import_tb.getSelectedRow(), 5);
        }
        else{
            JOptionPane.showMessageDialog(this,"Chose A Row To Edit.");
        }
    }//GEN-LAST:event_Edit_btActionPerformed

    private void Add_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btActionPerformed
        // TODO add your handling code here:
        if(tf_ImID.getText().equals("")||tf_PdName.getText().equals("")||tf_Cate.getText().equals("")||tf_spName.getText().equals("")||tf_Unit.getText().equals("")||tf_Price.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Not enough information.");
        }
        else
        {
            if(manage.ImportIDValid(this.tf_ImID.getText(), listimport)==false){
                JOptionPane.showMessageDialog(this,"Import Order Already Exist.");
            }else{
                Import imports = new Import();
                imports.setImID(this.tf_ImID.getText());
                imports.setPdName(this.tf_PdName.getText());
                imports.setCate(this.tf_Cate.getText());
                imports.setSpName(this.tf_spName.getText());
                imports.setUnit(Integer.parseInt(this.tf_Unit.getText()));
                imports.setPrice(Double.parseDouble(this.tf_Price.getText()));
                listimport.add(imports);

                manage.writeImportToFile(listimport);

                DefaultTableModel tblModel = new DefaultTableModel(header, 0);
                Vector data = null;
                for(Import im:listimport)
                {
                    data = new Vector();
                    data.add(im.getImID());
                    data.add(im.getPdName());
                    data.add(im.getCate());
                    data.add(im.getSpName());
                    data.add(im.getUnit());
                    data.add(im.getPrice());

                    tblModel.addRow(data);
                }
                this.import_tb.setModel(tblModel);
                JOptionPane.showMessageDialog(this,"Adding successful.");
            }

        }
    }//GEN-LAST:event_Add_btActionPerformed

    private void tf_UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_UnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_UnitActionPerformed

    private void Search_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btActionPerformed
        // TODO add your handling code here:
        String srch = tf_Search.getText();

        if (srch != null) {
            filter(srch);
        } else {
            JOptionPane.showMessageDialog(this,"Employee is not exist.");
        }
    }//GEN-LAST:event_Search_btActionPerformed

    private void import_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_import_tbMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbt = (DefaultTableModel) import_tb.getModel();
        int index = import_tb.getSelectedRow();
        String tbtImID = tbt.getValueAt(import_tb.getSelectedRow(), 0).toString();
        String tbtPdName = tbt.getValueAt(import_tb.getSelectedRow(), 1).toString();
        String tbtCate = tbt.getValueAt(import_tb.getSelectedRow(),2).toString();
        String tbtSpName = tbt.getValueAt(import_tb.getSelectedRow(), 3).toString();
        String tbtUnit = tbt.getValueAt(import_tb.getSelectedRow(), 4).toString();
        String tbtPrice = tbt.getValueAt(import_tb.getSelectedRow(), 5).toString();

        tf_ImID.setText(tbtImID);
        tf_PdName.setText(tbtPdName);
        tf_Cate.setText(tbtCate);
        tf_spName.setText(tbtSpName);
        tf_Unit.setText(tbtUnit);
        tf_Price.setText(tbtPrice);
    }//GEN-LAST:event_import_tbMouseClicked

    private void filter(String query){
    DefaultTableModel tbtModel = (DefaultTableModel) import_tb.getModel();
    TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(tbtModel);
    import_tb.setRowSorter(tr);

    tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    private String header[] = {"ID","Product Name","Category","Suppiler Name","Stock","Price"};
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_bt;
    private javax.swing.JButton Clear_bt;
    private javax.swing.JButton Delete_bt;
    private javax.swing.JButton Edit_bt;
    private javax.swing.JButton Return_bt;
    private javax.swing.JButton Search_bt;
    private javax.swing.JTable import_tb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField tf_Cate;
    private javax.swing.JTextField tf_ImID;
    private javax.swing.JTextField tf_PdName;
    private javax.swing.JTextField tf_Price;
    private javax.swing.JTextField tf_Search;
    private javax.swing.JTextField tf_Unit;
    private javax.swing.JTextField tf_spName;
    // End of variables declaration//GEN-END:variables
}
