/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject1;

/**
 *
 * @author Zero
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProductList_bt = new javax.swing.JButton();
        EmployeeList_bt = new javax.swing.JButton();
        SellH_bt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SellH_bt2 = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        SellH_bt1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("TOY KINGDOM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 390, -1));

        ProductList_bt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ProductList_bt.setForeground(new java.awt.Color(0, 0, 204));
        ProductList_bt.setText("Product list");
        ProductList_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductList_btActionPerformed(evt);
            }
        });
        jPanel1.add(ProductList_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 93));

        EmployeeList_bt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EmployeeList_bt.setForeground(new java.awt.Color(0, 0, 204));
        EmployeeList_bt.setText("Employee list");
        EmployeeList_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeList_btActionPerformed(evt);
            }
        });
        jPanel1.add(EmployeeList_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, 93));

        SellH_bt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SellH_bt.setForeground(new java.awt.Color(0, 0, 204));
        SellH_bt.setText("Import");
        SellH_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellH_btActionPerformed(evt);
            }
        });
        jPanel1.add(SellH_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 160, 93));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 90, 60));

        SellH_bt2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SellH_bt2.setForeground(new java.awt.Color(0, 0, 204));
        SellH_bt2.setText("Sell history");
        SellH_bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellH_bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(SellH_bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, 93));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject1/menu.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 0, 1110, 570));

        SellH_bt1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SellH_bt1.setForeground(new java.awt.Color(0, 0, 204));
        SellH_bt1.setText("Sell history");
        SellH_bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellH_bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(SellH_bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, 93));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeList_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeList_btActionPerformed
        this.setVisible(false);
        new EmployeeList().setVisible(true);
    }//GEN-LAST:event_EmployeeList_btActionPerformed

    private void ProductList_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductList_btActionPerformed
        this.setVisible(false);
        new ProductList().setVisible(true);
    }//GEN-LAST:event_ProductList_btActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SellH_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellH_btActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StoreSellHistory().setVisible(true);
    }//GEN-LAST:event_SellH_btActionPerformed

    private void SellH_bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellH_bt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SellH_bt1ActionPerformed

    private void SellH_bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellH_bt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SellH_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeList_bt;
    private javax.swing.JButton ProductList_bt;
    private javax.swing.JButton SellH_bt;
    private javax.swing.JButton SellH_bt1;
    private javax.swing.JButton SellH_bt2;
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
