/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject1;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Zero
 */
public class ProductList extends javax.swing.JFrame {
    StoreManage manage = new StoreManage();
    List<Product> listProduct = manage.readProductFromFile();
    /**
     * Creates new form ProductList
     */
    public ProductList() {
        initComponents();
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);    
        Vector data = null;
        for(Product pd:listProduct)
        {
            data = new Vector();
            data.add(pd.getPdID());
            data.add(pd.getPdName());
            data.add(pd.getCategory());
            data.add(pd.getPrice());
            data.add(pd.getStock());

            tblModel.addRow(data);
        }
        this.Product_tb.setModel(tblModel);
    }
    
    private String header[] = {"ID","Name","Category","Price","Stock"};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_PdID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_PdName = new javax.swing.JTextField();
        tf_Search = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Search_bt = new javax.swing.JButton();
        tf_PdCate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Product_tb = new javax.swing.JTable();
        label1 = new javax.swing.JLabel();
        tf_Price = new javax.swing.JTextField();
        Add_bt = new javax.swing.JButton();
        Clear_bt = new javax.swing.JButton();
        Edit_bt = new javax.swing.JButton();
        tf_Price3 = new javax.swing.JLabel();
        Delete_bt = new javax.swing.JButton();
        tf_Stock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Return_bt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(tf_PdID, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 160, 169, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setText("Product list");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 6, 350, 59));
        jPanel1.add(tf_PdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 205, 169, -1));

        tf_Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tf_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 83, 610, 45));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Category");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 162, -1, -1));

        Search_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search_bt.setText("SEARCH");
        Search_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btActionPerformed(evt);
            }
        });
        jPanel1.add(Search_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 101, 50));
        jPanel1.add(tf_PdCate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 169, -1));

        Product_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Product_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product_tbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Product_tb);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 850, 178));

        label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label1.setText("Price");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 207, -1, -1));
        jPanel1.add(tf_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 208, 169, -1));

        Add_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add_bt.setText("ADD");
        Add_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btActionPerformed(evt);
            }
        });
        jPanel1.add(Add_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 312, 87, 45));

        Clear_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear_bt.setText("CLEAR");
        Clear_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btActionPerformed(evt);
            }
        });
        jPanel1.add(Clear_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 103, 45));

        Edit_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Edit_bt.setText("EDIT");
        Edit_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_btActionPerformed(evt);
            }
        });
        jPanel1.add(Edit_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 101, 45));

        tf_Price3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_Price3.setText("Stock");
        jPanel1.add(tf_Price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        Delete_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete_bt.setText("DELETE");
        Delete_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btActionPerformed(evt);
            }
        });
        jPanel1.add(Delete_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 105, 45));

        tf_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_StockActionPerformed(evt);
            }
        });
        jPanel1.add(tf_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 248, 169, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 162, -1, -1));

        Return_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Return_bt.setText("RETURN");
        Return_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_btActionPerformed(evt);
            }
        });
        jPanel1.add(Return_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 103, 45));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject1/product.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 1100, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Product_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_tbMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbt = (DefaultTableModel) Product_tb.getModel();
        int index = Product_tb.getSelectedRow();
        String tbtPdID = tbt.getValueAt(Product_tb.getSelectedRow(), 0).toString();
        String tbtPdName = tbt.getValueAt(Product_tb.getSelectedRow(), 1).toString();
        String tbtCate = tbt.getValueAt(Product_tb.getSelectedRow(),2).toString();
        String tbtPrice = tbt.getValueAt(Product_tb.getSelectedRow(), 3).toString();
        String tbtStock = tbt.getValueAt(Product_tb.getSelectedRow(), 4).toString();
        
        tf_PdID.setText(tbtPdID);
        tf_PdName.setText(tbtPdName);
        tf_PdCate.setText(tbtCate);
        tf_Price.setText(tbtPrice);
        tf_Stock.setText(tbtStock);
    }//GEN-LAST:event_Product_tbMouseClicked

    private void Add_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btActionPerformed
        if(tf_PdID.getText().equals("")||tf_PdName.getText().equals("")||tf_PdCate.getText().equals("")||tf_Price.getText().equals("")||tf_Stock.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Not enough information.");
        }
        else
        {
            if(manage.ProductIDValid(this.tf_PdID.getText(), listProduct)==false){
                JOptionPane.showMessageDialog(this,"Product Already Exist.");
            }else{
                Product product = new Product();
                product.setpdID(this.tf_PdID.getText());
                product.setPdName(this.tf_PdName.getText());
                product.setCategory(this.tf_PdCate.getText());   
                product.setPrice(Double.parseDouble(this.tf_Price.getText()));     
                product.setPrice(Integer.parseInt(this.tf_Stock.getText()));
                listProduct.add(product);
                
                manage.writeProductToFile(listProduct);       
            
                DefaultTableModel tblModel = new DefaultTableModel(header, 0);    
                Vector data = null;
                for(Product pd:listProduct)
                {
                    data = new Vector();
                    data.add(pd.getPdID());
                    data.add(pd.getPdName());
                    data.add(pd.getCategory());
                    data.add(pd.getPrice());
                    data.add(pd.getStock());
                
                    tblModel.addRow(data);
                }
                this.Product_tb.setModel(tblModel);
                JOptionPane.showMessageDialog(this,"Adding successful.");
            }
            
        }
    }//GEN-LAST:event_Add_btActionPerformed

    private void Clear_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btActionPerformed
        // TODO add your handling code here:
        tf_PdID.setText("");
        tf_PdName.setText("");
        tf_PdCate.setText("");
        tf_Price.setText("");
        tf_Stock.setText("");
    }//GEN-LAST:event_Clear_btActionPerformed

    private void Edit_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_btActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbt = (DefaultTableModel) Product_tb.getModel();
        if(Product_tb.getSelectedRowCount()==1)
        {
            String pdID = tf_PdID.getText();
            String pdName = tf_PdName.getText();
            String pdCate = tf_PdCate.getText();
            double pdPrice = Double.parseDouble(tf_Price.getText());
            int pdStock = Integer.parseInt(tf_Stock.getText());
            listProduct.set(Product_tb.getSelectedRow(), new Product(pdID,pdName,pdCate,pdPrice,pdStock));
            manage.writeProductToFile(listProduct);
            
            tbt.setValueAt(pdID, Product_tb.getSelectedRow(), 0);
            tbt.setValueAt(pdName, Product_tb.getSelectedRow(), 1);        
            tbt.setValueAt(pdCate, Product_tb.getSelectedRow(), 2);
            tbt.setValueAt(pdPrice, Product_tb.getSelectedRow(), 3);
            tbt.setValueAt(pdStock, Product_tb.getSelectedRow(), 4);
        }
        else{
            JOptionPane.showMessageDialog(this,"Chose A Row To Edit.");
        }
    }//GEN-LAST:event_Edit_btActionPerformed

    private void Delete_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbtModel = (DefaultTableModel) Product_tb.getModel();
        
        if(Product_tb.getSelectedRowCount()==1)
        {
            int i=Product_tb.getSelectedRow();
            tbtModel.removeRow(Product_tb.getSelectedRow());
            listProduct.remove(i); 
            manage.writeProductToFile(listProduct);
        }
        else {
            if(Product_tb.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"No Data.");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Chose A Row To Delete.");
            }
        }
    }//GEN-LAST:event_Delete_btActionPerformed

    private void tf_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_StockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_StockActionPerformed

    private void Return_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_btActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_Return_btActionPerformed

    private void Search_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btActionPerformed
        // TODO add your handling code here:
        String srch = tf_Search.getText();
    
        if (srch != null) {
            filter(srch);
        } else {
            JOptionPane.showMessageDialog(this,"Employee is not exist.");
        }
    }//GEN-LAST:event_Search_btActionPerformed
    
    private void filter(String query){
    DefaultTableModel tbtModel = (DefaultTableModel) Product_tb.getModel();
    TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(tbtModel);
    Product_tb.setRowSorter(tr);

    tr.setRowFilter(RowFilter.regexFilter(query));
    }
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_bt;
    private javax.swing.JButton Clear_bt;
    private javax.swing.JButton Delete_bt;
    private javax.swing.JButton Edit_bt;
    private javax.swing.JTable Product_tb;
    private javax.swing.JButton Return_bt;
    private javax.swing.JButton Search_bt;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField tf_PdCate;
    private javax.swing.JTextField tf_PdID;
    private javax.swing.JTextField tf_PdName;
    private javax.swing.JTextField tf_Price;
    private javax.swing.JLabel tf_Price3;
    private javax.swing.JTextField tf_Search;
    private javax.swing.JTextField tf_Stock;
    // End of variables declaration//GEN-END:variables
}
