/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject1;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author A
 */
public class StoreSellHistory extends javax.swing.JFrame {
    StoreManage manage = new StoreManage();
    List<SellHistory> listSell = manage.readSellFromFile();
    /**
     * Creates new form StoreSellHistory
     */
    public StoreSellHistory() {
        initComponents();
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);    
        Vector data = null;
        for(SellHistory sh:listSell)
        {
            data = new Vector();
            data.add(sh.getShID());
            data.add(sh.getPdName());
            data.add(sh.getCate());
            data.add(sh.getEmpName());
            data.add(sh.getUnit());
            data.add(sh.getPrice());

            tblModel.addRow(data);
        }
        this.Sell_tb.setModel(tblModel);
    }
    
    private String header[] = {"ID","Product Name","Category","Emp. Name","Stock","Price"};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Sell_tb = new javax.swing.JTable();
        tf_Search = new javax.swing.JTextField();
        Search_bt = new javax.swing.JButton();
        Add_bt = new javax.swing.JButton();
        Edit_bt = new javax.swing.JButton();
        Delete_bt = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_PdName = new javax.swing.JTextField();
        tf_Price = new javax.swing.JTextField();
        tf_ShID = new javax.swing.JTextField();
        l = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_Unit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_EmpName = new javax.swing.JTextField();
        Clear_bt = new javax.swing.JButton();
        Return_bt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_Cate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Sell History");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Sell_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Category", "Employee", "Unit", "Price"
            }
        ));
        Sell_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sell_tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Sell_tb);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 620, 187));
        jPanel1.add(tf_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 436, 34));

        Search_bt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Search_bt.setText("SEARCH");
        Search_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btActionPerformed(evt);
            }
        });
        jPanel1.add(Search_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 97, 34));

        Add_bt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Add_bt.setText("ADD");
        Add_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btActionPerformed(evt);
            }
        });
        jPanel1.add(Add_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 90, 44));

        Edit_bt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Edit_bt.setText("EDIT");
        Edit_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_btActionPerformed(evt);
            }
        });
        jPanel1.add(Edit_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 80, 44));

        Delete_bt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Delete_bt.setText("DELETE");
        Delete_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btActionPerformed(evt);
            }
        });
        jPanel1.add(Delete_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 80, 44));

        label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label1.setText("Price");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Emp. Name");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));
        jPanel1.add(tf_PdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 169, -1));
        jPanel1.add(tf_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 169, -1));
        jPanel1.add(tf_ShID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 169, -1));

        l.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l.setText("Unit");
        jPanel1.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Toy Name");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        tf_Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_UnitActionPerformed(evt);
            }
        });
        jPanel1.add(tf_Unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 169, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));
        jPanel1.add(tf_EmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 169, -1));

        Clear_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear_bt.setText("CLEAR");
        Clear_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btActionPerformed(evt);
            }
        });
        jPanel1.add(Clear_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, 45));

        Return_bt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Return_bt.setText("RETURN");
        Return_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_btActionPerformed(evt);
            }
        });
        jPanel1.add(Return_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 110, 45));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Category");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));
        jPanel1.add(tf_Cate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 169, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject1/sell.jpg"))); // NOI18N
        jLabel2.setName(""); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 710, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_UnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_UnitActionPerformed

    private void Clear_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btActionPerformed
        // TODO add your handling code here:
        tf_ShID.setText("");
        tf_PdName.setText("");
        tf_Cate.setText("");
        tf_EmpName.setText("");
        tf_Unit.setText("");
        tf_Price.setText("");
    }//GEN-LAST:event_Clear_btActionPerformed

    private void Return_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_btActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_Return_btActionPerformed

    private void Add_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btActionPerformed
        // TODO add your handling code here:
        if(tf_ShID.getText().equals("")||tf_PdName.getText().equals("")||tf_Cate.getText().equals("")||tf_EmpName.getText().equals("")||tf_Unit.getText().equals("")||tf_Price.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Not enough information.");
        }
        else
        {
            if(manage.SellIDValid(this.tf_ShID.getText(), listSell)==false){
                JOptionPane.showMessageDialog(this,"Sell Already Exist.");
            }else{
                SellHistory sellHistory = new SellHistory();
                sellHistory.setShID(this.tf_ShID.getText());
                sellHistory.setPdName(this.tf_PdName.getText());
                sellHistory.setCate(this.tf_Cate.getText());   
                sellHistory.setEmpName(this.tf_EmpName.getText());
                sellHistory.setUnit(Integer.parseInt(this.tf_Unit.getText()));
                sellHistory.setPrice(Double.parseDouble(this.tf_Price.getText()));                    
                listSell.add(sellHistory);
                
                manage.writeSellToFile(listSell);       
            
                DefaultTableModel tblModel = new DefaultTableModel(header, 0);    
                Vector data = null;
                for(SellHistory sh:listSell)
                {
                    data = new Vector();
                    data.add(sh.getShID());
                    data.add(sh.getPdName());
                    data.add(sh.getCate());
                    data.add(sh.getEmpName());
                    data.add(sh.getUnit());
                    data.add(sh.getPrice());
                
                    tblModel.addRow(data);
                }
                this.Sell_tb.setModel(tblModel);
                JOptionPane.showMessageDialog(this,"Adding successful.");
            }
            
        }
    }//GEN-LAST:event_Add_btActionPerformed

    private void Sell_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sell_tbMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbt = (DefaultTableModel) Sell_tb.getModel();
        int index = Sell_tb.getSelectedRow();
        String tbtShID = tbt.getValueAt(Sell_tb.getSelectedRow(), 0).toString();
        String tbtPdName = tbt.getValueAt(Sell_tb.getSelectedRow(), 1).toString();
        String tbtCate = tbt.getValueAt(Sell_tb.getSelectedRow(),2).toString();
        String tbtEmpName = tbt.getValueAt(Sell_tb.getSelectedRow(), 3).toString();
        String tbtUnit = tbt.getValueAt(Sell_tb.getSelectedRow(), 4).toString();
        String tbtPrice = tbt.getValueAt(Sell_tb.getSelectedRow(), 5).toString();
        
        tf_ShID.setText(tbtShID);
        tf_PdName.setText(tbtPdName);
        tf_Cate.setText(tbtCate);
        tf_EmpName.setText(tbtEmpName);
        tf_Unit.setText(tbtUnit);
        tf_Price.setText(tbtPrice);
    }//GEN-LAST:event_Sell_tbMouseClicked

    private void Edit_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_btActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbt = (DefaultTableModel) Sell_tb.getModel();
        if(Sell_tb.getSelectedRowCount()==1)
        {
            String shID = tf_ShID.getText();
            String pdName = tf_PdName.getText();
            String pdCate = tf_Cate.getText();
            String empName = tf_EmpName.getText();
            int pdUnit = Integer.parseInt(tf_Unit.getText());
            double pdPrice = Double.parseDouble(tf_Price.getText());
            
            listSell.set(Sell_tb.getSelectedRow(), new SellHistory(shID,pdName,pdCate,empName,pdUnit,pdPrice));
            manage.writeSellToFile(listSell);
            
            tbt.setValueAt(shID, Sell_tb.getSelectedRow(), 0);
            tbt.setValueAt(pdName, Sell_tb.getSelectedRow(), 1);        
            tbt.setValueAt(pdCate, Sell_tb.getSelectedRow(), 2);
            tbt.setValueAt(empName, Sell_tb.getSelectedRow(), 3);
            tbt.setValueAt(pdUnit, Sell_tb.getSelectedRow(), 4);
            tbt.setValueAt(pdPrice, Sell_tb.getSelectedRow(), 5);
        }
        else{
            JOptionPane.showMessageDialog(this,"Chose A Row To Edit.");
        }
    }//GEN-LAST:event_Edit_btActionPerformed

    private void Delete_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbtModel = (DefaultTableModel) Sell_tb.getModel();
        
        if(Sell_tb.getSelectedRowCount()==1)
        {
            int i=Sell_tb.getSelectedRow();
            tbtModel.removeRow(Sell_tb.getSelectedRow());
            listSell.remove(i); 
            manage.writeSellToFile(listSell);
        }
        else {
            if(Sell_tb.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"No Data.");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Chose A Row To Delete.");
            }
        }
    }//GEN-LAST:event_Delete_btActionPerformed

    private void Search_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btActionPerformed
        // TODO add your handling code here:
        String srch = tf_Search.getText();
    
        if (srch != null) {
            filter(srch);
        } else {
            JOptionPane.showMessageDialog(this,"Employee is not exist.");
        }
    }//GEN-LAST:event_Search_btActionPerformed
    
    private void filter(String query){
    DefaultTableModel tbtModel = (DefaultTableModel) Sell_tb.getModel();
    TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(tbtModel);
    Sell_tb.setRowSorter(tr);

    tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreSellHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreSellHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreSellHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreSellHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreSellHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_bt;
    private javax.swing.JButton Clear_bt;
    private javax.swing.JButton Delete_bt;
    private javax.swing.JButton Edit_bt;
    private javax.swing.JButton Return_bt;
    private javax.swing.JButton Search_bt;
    private javax.swing.JTable Sell_tb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField tf_Cate;
    private javax.swing.JTextField tf_EmpName;
    private javax.swing.JTextField tf_PdName;
    private javax.swing.JTextField tf_Price;
    private javax.swing.JTextField tf_Search;
    private javax.swing.JTextField tf_ShID;
    private javax.swing.JTextField tf_Unit;
    // End of variables declaration//GEN-END:variables
}
